// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: demo.proto

package demo

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_demo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_demo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RestaurantLikeStatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResIds        []int32                `protobuf:"varint,1,rep,packed,name=resIds,proto3" json:"resIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantLikeStatRequest) Reset() {
	*x = RestaurantLikeStatRequest{}
	mi := &file_demo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantLikeStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantLikeStatRequest) ProtoMessage() {}

func (x *RestaurantLikeStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantLikeStatRequest.ProtoReflect.Descriptor instead.
func (*RestaurantLikeStatRequest) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{2}
}

func (x *RestaurantLikeStatRequest) GetResIds() []int32 {
	if x != nil {
		return x.ResIds
	}
	return nil
}

type RestaurantLikeStatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        map[int32]int32        `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestaurantLikeStatResponse) Reset() {
	*x = RestaurantLikeStatResponse{}
	mi := &file_demo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestaurantLikeStatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestaurantLikeStatResponse) ProtoMessage() {}

func (x *RestaurantLikeStatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_demo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestaurantLikeStatResponse.ProtoReflect.Descriptor instead.
func (*RestaurantLikeStatResponse) Descriptor() ([]byte, []int) {
	return file_demo_proto_rawDescGZIP(), []int{3}
}

func (x *RestaurantLikeStatResponse) GetResult() map[int32]int32 {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_demo_proto protoreflect.FileDescriptor

const file_demo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"demo.proto\x12\x04demo\x1a3third_party/googleapis/google/api/annotations.proto\"\"\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\")\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\x19RestaurantLikeStatRequest\x12\x16\n" +
	"\x06resIds\x18\x01 \x03(\x05R\x06resIds\"\x9d\x01\n" +
	"\x1aRestaurantLikeStatResponse\x12D\n" +
	"\x06result\x18\x01 \x03(\v2,.demo.RestaurantLikeStatResponse.ResultEntryR\x06result\x1a9\n" +
	"\vResultEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x012\x9c\x02\n" +
	"\fHelloService\x12M\n" +
	"\x05Hello\x12\x12.demo.HelloRequest\x1a\x13.demo.HelloResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/example/echo\x12:\n" +
	"\vHelloStream\x12\x12.demo.HelloRequest\x1a\x13.demo.HelloResponse\"\x000\x01\x12\x80\x01\n" +
	"\x15GetRestaurantLikeStat\x12\x1f.demo.RestaurantLikeStatRequest\x1a .demo.RestaurantLikeStatResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/restaurant/like-statsB\bZ\x06./demob\x06proto3"

var (
	file_demo_proto_rawDescOnce sync.Once
	file_demo_proto_rawDescData []byte
)

func file_demo_proto_rawDescGZIP() []byte {
	file_demo_proto_rawDescOnce.Do(func() {
		file_demo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)))
	})
	return file_demo_proto_rawDescData
}

var file_demo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_demo_proto_goTypes = []any{
	(*HelloRequest)(nil),               // 0: demo.HelloRequest
	(*HelloResponse)(nil),              // 1: demo.HelloResponse
	(*RestaurantLikeStatRequest)(nil),  // 2: demo.RestaurantLikeStatRequest
	(*RestaurantLikeStatResponse)(nil), // 3: demo.RestaurantLikeStatResponse
	nil,                                // 4: demo.RestaurantLikeStatResponse.ResultEntry
}
var file_demo_proto_depIdxs = []int32{
	4, // 0: demo.RestaurantLikeStatResponse.result:type_name -> demo.RestaurantLikeStatResponse.ResultEntry
	0, // 1: demo.HelloService.Hello:input_type -> demo.HelloRequest
	0, // 2: demo.HelloService.HelloStream:input_type -> demo.HelloRequest
	2, // 3: demo.HelloService.GetRestaurantLikeStat:input_type -> demo.RestaurantLikeStatRequest
	1, // 4: demo.HelloService.Hello:output_type -> demo.HelloResponse
	1, // 5: demo.HelloService.HelloStream:output_type -> demo.HelloResponse
	3, // 6: demo.HelloService.GetRestaurantLikeStat:output_type -> demo.RestaurantLikeStatResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_demo_proto_init() }
func file_demo_proto_init() {
	if File_demo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_demo_proto_rawDesc), len(file_demo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demo_proto_goTypes,
		DependencyIndexes: file_demo_proto_depIdxs,
		MessageInfos:      file_demo_proto_msgTypes,
	}.Build()
	File_demo_proto = out.File
	file_demo_proto_goTypes = nil
	file_demo_proto_depIdxs = nil
}
